on:
  push:
    branches:
    - main
jobs:
  update_default:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - id: update_default
        run: |
          SBT_VERSION=$(grep '^sbt\.version' "project/build.properties" | tr '=\r' ' ' | awk '{ print $2; }')
          yq e -i ".inputs.sbt-runner-version.default = \"${SBT_VERSION}\"" action.yml
          git add action.yml
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github actions"
          if git commit -m "update default sbt version to ${SBT_VERSION}"; then
            git push -f origin HEAD:"update-default-sbt-${SBT_VERSION}"
            echo "pushed=true" >> $GITHUB_OUTPUT
            echo "sbt_version=${SBT_VERSION}" >> $GITHUB_OUTPUT
          else
            echo "pushed=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: steps.update_default.outputs.pushed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          title: "deps: Update sbt version"
          branch: generation
          base: ${{ github.head_ref }}
